Fix KeyError when using GitHub (#25)
`pull_request` field is not required in an `issue` object

https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28

```
% potodo --api-url 'https://api.github.com/repos/python/python-docs-pl/issues?state=open'
Traceback (most recent call last):
  File "…/bin/potodo", line 12, in <module>
    sys.exit(main())
             ~~~~^^
  File "…/site-packages/potodo/potodo.py", line 132, in main
    po_directories.fetch_issues(args.api_url)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "…/site-packages/potodo/po_file.py", line 152, in fetch_issues
    directory.fetch_issues(api_url)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "…/site-packages/potodo/po_file.py", line 333, in fetch_issues
    issue_reservations = get_issue_reservations(api_url)
  File "…/site-packages/potodo/forge_api.py", line 45, in get_issue_reservations
    is_pull_request = issue["pull_request"] is not None
                      ~~~~~^^^^^^^^^^^^^^^^
KeyError: 'pull_request'
```

Co-authored-by: Maciej Olko <maciej.olko@affirm.com>
Reviewed-on: https://git.afpy.org/AFPy/potodo/pulls/25
Reviewed-by: Julien Palard <julien@palard.fr>
Co-authored-by: maciek <maciej.olko@gmail.com>
Co-committed-by: maciek <maciej.olko@gmail.com>